name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: self-hosted

    env:
      Solution_Name: WarehouseAssistant.sln                
      Test_Project_Path: WarehouseAssistant.WebApi.Tests/WarehouseAssistant.WebApi.Tests.csproj
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Execute all unit tests in the solution
    # - name: Execute unit tests
    #  run: dotnet test

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: dotnet restore
      working-directory: src/WarehouseAssistant.WebApi
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Build the application
      run: dotnet build 
      working-directory: src/WarehouseAssistant.WebApi
